apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k10-nfs
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /export
    server: 10.100.152.7
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-k10-nfs
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-k10-nfs
  storageClassName: ""