apiVersion: v1
kind: Secret
metadata:
  name: k10-ingress-tls
  namespace: kasten-io
type: kubernetes.io/tls
stringData:
  tls.crt: | # Set your Kasten certificate below
    -----BEGIN CERTIFICATE-----
    MIIFiDCCBHCgAwIBAgITUwAAAI0FEL7smbpEigABAAAAjTANBgkqhkiG9w0BAQsF
    ADBPMRQwEgYKCZImiZPyLGQBGRYEZGVtb.........
    -----END CERTIFICATE-----
  tls.key: | # Set your Kasten private key below
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAsxCU+mvz0Tu4SbD/+5zbzILpkJ7irU8vuYt6cBI+dA/8ZHPM
    qYUPYLJhyHMglc+7aL1/3zrC8tt9DwB...........
    -----END RSA PRIVATE KEY-----
